version: "3.8"
services:
    gateway:
        image: nginx:1.19.8-alpine
        ports:
            - 8000:8000
        networks: 
            - backend
        volumes:
            - ./gateway/nginx.conf:/etc/nginx/nginx.conf
            - ./gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
        depends_on: 
            - authentication-service
            - user-service
            - post-service
    db:
        restart: always
        image: postgres
        container_name: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks: 
            - backend
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
    post-service:
        restart: always
        image: post-service:compose_build
        build:
            context: ./post-service
            dockerfile: Dockerfile
        networks:
            - backend
        environment:
            DBHOST: db
            USER: postgres
            PASSWORD: postgres
            DBNAME: postgres
            DBPORT: 5432
            PORT: 8000
        depends_on:
            - db
        volumes:
            - ./user-service/files:/go/app/files
    user-service:
        restart: always
        image: user-service:compose_build
        build:
            context: ./user-service
            dockerfile: Dockerfile
        networks:
            - backend
        environment:
            DBHOST: db
            USER: postgres
            PASSWORD: postgres
            DBNAME: postgres
            DBPORT: 5432
            PORT: 8000
        depends_on:
            - db 
        volumes:
            - ./user-service/files:/go/app/files
    authentication-service:
        restart: always
        image: authentication-service:compose_build
        build:
            context: ./authentication-service
            dockerfile: Dockerfile
        networks: 
            - backend
        environment:
            DBHOST: db
            USER: postgres
            PASSWORD: postgres
            DBNAME: postgres
            DBPORT: 5432
            PORT: 8000
        depends_on:
            - db 
        volumes:
            - ./user-service/files:/go/app/files  
networks: 
    backend:
        name: nistagram
        driver: bridge
volumes:
    pgdata: